{{- if .Values.persistence.enabled }}
{{- if .Values.persistence.data.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "workflow-layer.fullname" . }}-data-pvc
  labels:
    {{- include "workflow-layer.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.data.accessMode }}
  storageClassName: {{ .Values.persistence.data.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size }}
{{- end }}
---
{{- if .Values.persistence.templates.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "workflow-layer.fullname" . }}-templates-pvc
  labels:
    {{- include "workflow-layer.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.templates.accessMode }}
  storageClassName: {{ .Values.persistence.templates.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.templates.size }}
{{- end }}
---
{{- if .Values.enablePersistentLogs }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "workflow-layer.fullname" . }}-logs-pvc
  labels:
    {{- include "workflow-layer.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.logs.accessMode }}
  storageClassName: {{ .Values.persistence.logs.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.logs.size }}
{{- end }}
{{- end }}
